DEFAULT:
  x_min: 90
  x_max: 570
  y_min: 200
  y_max: 330

WS01:
  x_min: 90
  x_max: 570
  y_min: 200
  y_max: 300 

WS02:
  x_min: 50
  x_max: 530
  y_min: 180
  y_max: 380 

WS03:
  x_min: 90
  x_max: 570
  y_min: 200
  y_max: 370

WS04:
  x_min: 60
  x_max: 570
  y_min: 190
  y_max: 370

WS05:
  x_min: 90
  x_max: 570
  y_min: 250
  y_max: 390





